name: mes_cycles
description: "Suivre ses cycles"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  url_launcher: ^6.2.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  table_calendar: ^3.0.9
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


#flutter_launcher_icons:
#  android: "launcher_icon"
#  image_path: "assets/icon/launcher_icon.png"
#  min_sdk_android: 21 # android min sdk min:16, default 21
#  ios: "AppIcon"
#  remove_alpha_ios: true